<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Right?</th>
      <th>Latex</th>
      <th>Action</th>
    </tr>
  </thead>
<?php foreach ($this->answers as $index=>$answer) : ?>
  <tr>
    <td><input type="text" name="answers[<?php echo $index;?>][label]" value="<?php if (!empty($answer['label'])) echo $answer['label'];?>" size="3" maxlength="3"></td>
         <td><input type="radio" name="rightAnswer" value="<?php echo $index;?>"<?php if (!empty($answer['is_right']) && $answer['is_right'] == 1) echo " checked";?>></td>
         <td><textarea name="answers[<?php echo $index; ?>][answer_latex]" rows="3" cols="50"><?php if (!empty($answer['answer_latex'])) echo $answer['answer_latex'];?></textarea></td>
    <td><input type="submit" name="deleteMCAnswer[<?php echo $index;?>]" value="Delete"></td>
<?php if (isset($answer['answer_id'])) : ?>
    <input type="hidden" name="answers[<?php echo $index; ?>][answer_id]" value="<?php echo $answer['answer_id'];?>">
<?php endif; ?>
  </tr>
<?php endforeach; ?>
</table>

<br>

<center>
         <input type="submit" name="addMCAnswer" value="Add another answer">
</center>
