<div>
  		<fieldset>  
  			<legend>Conversion options</legend>
  			<input type="checkbox" name="usejpeg" />
  			<label for="usejpeg">Use jpeg conversion. <strong>quality loss and bigger file size. Only use if you enconter problem with the normal conversion</strong></label><br/>
  			
  			<input type="checkbox" name="noswf" />
  			<label for="usejpeg">Do not generate swf.</label><br/>
  			
  		</fieldset>
		</div>