<form method="post">
<table class="question">
  <thead class="question">
  	<tr>
             <th>Language</th>
             <th>Source</th>
             <th>Title</th>
  	</tr>
  </thead>
  <tr>
    <td>
      <SELECT MULTIPLE name="languages[]" SIZE="10">
        <?php foreach($this->allFilterOptions['languages'] as $language) : ?>
          <option value="<?php echo $language['language_id']; ?>"
                  <?php if (in_array($language['language_id'], $this->selectedFilterOptions['languages'])) echo " selected";?>>
                  <?php echo $this->echoIfNotEmpty($language['name'],$language['language_id'],"Language#"); ?>
          </option>
        <?php endforeach; ?>
      </SELECT>
    </td>
    <td>
      <select multiple name="sources[]" SIZE="10">
      <?php foreach($this->allFilterOptions['sources'] as $source) : ?>
        <option value="<?php echo $source['source_id']; ?>"
                <?php if (in_array($source['source_id'], $this->selectedFilterOptions['sources'])) echo " selected";?>>
                <?php echo $this->echoIfNotEmpty($source['name'],$source['source_id'],"Source#"); ?>
        </option>
      <?php endforeach; ?>
      </SELECT>
    </td>

    <td>
      <select multiple name="titles[]" SIZE="10">
      <?php foreach($this->allFilterOptions['titles'] as $title) : ?>
        <option value="<?php echo $title['title_id']; ?>"
                <?php if (in_array($title['title_id'], $this->selectedFilterOptions['titles'])) echo " selected"; ?>>
                <?php echo $this->echoIfNotEmpty($title['name'],$title['title_id'],"Title#"); ?>
        </option>
      <?php endforeach; ?>
      </select>
    </td>
  </tr>
  <thead>
    <tr>
             <th colspan="2">Subject and Category</th>
             <th>Answer type</th>
    </tr>
  </thead>
  <tr>
    <td colspan="2">
      <SELECT MULTIPLE name="categories[]" SIZE="10">
        <?php foreach($this->allFilterOptions['categories'] as $category) : ?>
          <option value="<?php echo $category['category_id']; ?>"
                  <?php if (in_array($category['category_id'], $this->selectedFilterOptions['categories'])) echo " selected";?>>
                  <?php echo $this->echoIfNotEmpty($category['subject_name'],$category['subject_id'],"Subject#") . " --> " . $this->echoIfNotEmpty($category['category_name'],$category['category_id'],"Category#"); ?>
          </option>
        <?php endforeach; ?>
      </SELECT>
    </td>

    <td>
      <SELECT MULTIPLE name="answer_types[]" SIZE="10">
        <?php foreach($this->allFilterOptions['answer_types'] as $answer_type) : ?>
          <option value="<?php echo $answer_type['answer_type_id']; ?>"
                  <?php if (in_array($answer_type['answer_type_id'], $this->selectedFilterOptions['answer_types'])) echo " selected";?>>
                  <?php echo $this->echoIfNotEmpty($answer_type['name'],$answer_type['answer_type_id'],"AnswerType#"); ?>
          </option>
        <?php endforeach; ?>
      </SELECT>
    </td>
  </tr>
  <thead>
    <tr>
             <th>Creator</th>
             <th colspan="2">Latex text keywords (space separated)</th>
    </tr>
  </thead>

  <tr>             
             <td rowspan="3">
               <select multiple name="creators[]" SIZE="10">
                 <option value="<?php echo $this->user->user_id ?>"
                         <?php if (in_array($this->user->user_id, $this->selectedFilterOptions['creators'])) echo " selected";?>>
                         <?php echo $this->echoIfNotEmpty($this->user->username,$this->user->user_id,"User#"); ?>
                 </option>
                 <?php foreach($this->allFilterOptions['question_creators'] as $creator) : ?>
                   <?php if ($creator['user_id']==$this->user->user_id) continue; ?>
                   <option value="<?php echo $creator['user_id']; ?>"
                           <?php if (in_array($creator['user_id'], $this->selectedFilterOptions['creators'])) echo " selected";?>>
                           <?php echo $this->echoIfNotEmpty($creator['username'],$creator['user_id'],"User#"); ?>
                   </option>
                 <?php endforeach; ?>
               </select>
             </td>

             <td colspan="2" valign="top">
               <input type="text" size="50" name="keywords" value="<?php foreach($this->selectedFilterOptions['keywords'] as $keyword) echo $keyword." "; ?>">
             </td>
  </tr>
  <tr>
             <th colspan="2">Options</th>
  </tr>
  <tr>
             <td colspan="2">
 <input type="checkbox" name="enabled"<?php if (in_array("1", $this->selectedFilterOptions['is_valid'])) echo " checked";?>>Enabled
 <input type="checkbox" name="disabled"<?php if (in_array("0", $this->selectedFilterOptions['is_valid'])) echo " checked";?>>Disabled
 <input type="checkbox" name="animated"<?php if (in_array("1", $this->selectedFilterOptions['is_animated'])) echo " checked";?>>Animated
 <input type="checkbox" name="unanimated"<?php if (in_array("0", $this->selectedFilterOptions['is_animated'])) echo " checked";?>>Not animated
             </td>
  </tr>

  <tr>
    <td colspan="3">
      <INPUT TYPE="SUBMIT" NAME="question_filter" VALUE="GO!">
    </td>
  </tr>
</table>
</form>
