<div>
  <form method="post" action="add">
    <input type="hidden" name="step" value="4" />
    <fieldset>  
        <legend>Question details</legend>
    <table>
     <tr>
       <td>Language</td>
       <td><?php echo $this->session->language_name; ?></td>
     </tr>
     <tr>
       <td>Subject</td>
       <td><?php echo $this->session->subject_name; ?></td>
     </tr>
     <tr>
       <td>Answer type</td>
       <td><?php echo $this->session->answer_type_name; ?></td>
     </tr>
     <tr>
       <td>Category</td>
       <td><?php echo $this->session->category_name; ?></td>
     </tr>

		<tr>
			<td><label for="questionLatex">Latex Question</label></td>
			<td><textarea name="questionLatex" rows="15" cols="50"></textarea></td>
		</tr>
		<tr>
			<td><label for="feedbackLatex">Feedback latex</label></td>
			<td><textarea name="feedbackLatex" rows="15" cols="50"></textarea></td>
		</tr>
		<?php if ($this->session->answer_type_tag == 'MULTIPLE_CHOICE') : ?>
				<tr>
				  <td><label for="choiceA">Choice A</label></td>
				  <td><textarea rows="3" cols="50" name="choiceA"></textarea></td>
				</tr>
				<tr>
				  <td><label for="choiceB">Choice B</label></td>
				  <td><textarea rows="3" cols="50" name="choiceB"></textarea></td>
				</tr>
				<tr>
				  <td><label for="choiceC">Choice C</label></td>
				  <td><textarea rows="3" cols="50" name="choiceC"></textarea></td>
				</tr>
				<tr>
				  <td><label for="choiceD">Choice D</label></td>
				  <td><textarea rows="3" cols="50" name="choiceD"></textarea></td>
				</tr>
				<tr>
          <td><label for="goodAnswer">Good answer</label></td>
          <td><input type="text" name="goodAnswer"></td>
        </tr>
		<?php endif; ?>
		<?php if ($this->session->answer_type_tag == 'TRUE_FALSE') : ?>
		  <tr>
        <td><label for="goodAnswer">Answer</label></td>
        <td>True <input type="radio" name="goodAnswer" value="true"><br/>False<input type="radio" name="goodAnswer" value="false"></td>
      </tr>
		<?php endif; ?>
		<?php if ($this->session->answer_type_tag == 'SHORT_TEXT') : ?>
      <tr>
        <td><label for="goodAnswer">Answer</label></td>
        <td><input type="text" name="goodAnswer" /></td>
      </tr>
    <?php endif; ?>
		
		</table>
		</fieldset>
		
		<div>
			<fieldset>  
			<legend>Levels</legend>
			<table>
			<thead>
			 <tr>
			   <th>Level</th>
			   <th>Difficulty</th>
			 </tr>
			</thead>
  			<?php foreach($this->levels as $level) : ?>
  			 <tr>
  			   <td><?php echo $level->name ?></td>
  			   <td>
  			     <select name="levelValue[<?php echo $level->level_id; ?>]" />
  			       <option>0</option>
  			       <option>1</option>
  			       <option>2</option>
  			       <option>3</option>
  			       <option>4</option>
  			       <option>5</option>
  			       <option>6</option>
  			     </select>
  			   </td>
  			</tr>  			
  			<?php endforeach; ?>
			</table>
			</fieldset>
		</div>
		<div>
  		<fieldset>  
  			<legend>Conversion options</legend>
  			<input type="checkbox" name="usejpeg" />
  			<label for="usejpeg">Use jpeg conversion. <strong>quality loss and bigger file size. Only use if you enconter problem with the normal conversion</strong></label><br/>
  			
  			<input type="checkbox" name="noswf" />
  			<label for="usejpeg">Do not generate swf.</label><br/>
  			
  		</fieldset>
		</div>
		<div>
			<fieldset>  
				<legend>Comment (optional)</legend>
				<textarea name="comment" rows="8" cols="80"></textarea>
			</fieldset>
		</div>
		<div>
			<input type="submit" />
		</div>
	</form>
</div>