<?php $numberOfPages=ceil(count($this->questions)/$this->questionsPerPage); ?>
<?php $firstIndex = $this->questionsPerPage*($this->currentPageNumber-1); ?>
<?php $lastIndex = min($firstIndex+$this->questionsPerPage, count($this->questions)); ?>

<table>
  <tr>
    <td><form method="post"><input type="submit" name="first" value="<<"></form></td>
    <td><form method="post"><input type="submit" name="prev" value="<"></form></td>
    <td><form method="post"><input type="submit" name="next" value=">"></form></td>
    <td><form method="post"><input type="submit" name="last" value=">>"></form></td>
    <td><form method="post"> 
          Jump to page 
          <SELECT name="page" onchange="this.form.submit();">
            <?php for($i=1; $i<=$numberOfPages; ++$i) : ?>
              <option value="<?php echo $i; ?>"<?php if ($i == $this->currentPageNumber) echo " selected"; ?>><?php echo $i; ?></option>
            <?php endfor; ?>
          </SELECT>
        </form>
    </td>
  </tr>
</table>

<table class="question">
  <thead class="question">
  	<tr>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/question_id">ID</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/subject_name">Subject</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/category_name">Category</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/source_name">Source</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/title_name">Title</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/answer_type_name">Type</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/username">Creator</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/question_latex">Latex</a></th>
             <th>Action</th>
  	</tr>
  </thead>

<?php for($i = $firstIndex; $i < $lastIndex; ++$i) :?>
<?php
          $this->question = $this->questions[$i];
?>

    <tr> 
      <td><?php echo $this->escape($this->question['question_id']);?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($this->question['subject_name'],$this->question['subject_id'],"Subject#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($this->question['category_name'],$this->question['category_id'],"Category#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($this->question['source_name'],$this->question['source_id'],"Source#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($this->question['title_name'],$this->question['title_id'],"Title#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($this->question['answer_type_name'],$this->question['answer_type_id'],"AnswerType#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($this->question['username'],$this->question['user_id'],"User#"));?></td>
      <td><?php echo $this->escape(substr($this->question['question_latex'],0, 75));?></td>
      <td><?php echo $this->render('question/_action.phtml'); ?></td>
    </tr>
<?php endfor; ?>
  </table>
<table>
  <tr>
    <td><form method="post"><input type="submit" name="first" value="<<"></form></td>
    <td><form method="post"><input type="submit" name="prev" value="<"></form></td>
    <td><form method="post"><input type="submit" name="next" value=">"></form></td>
    <td><form method="post"><input type="submit" name="last" value=">>"></form></td>
    <td><form method="post"> 
          Jump to page 
          <SELECT name="page" onchange="this.form.submit();">
            <?php for($i=1; $i<=$numberOfPages; ++$i) : ?>
              <option value="<?php echo $i; ?>"<?php if ($i == $this->currentPageNumber) echo " selected"; ?>><?php echo $i; ?></option>
            <?php endfor; ?>
          </SELECT>
        </form>
    </td>
  </tr>
</table>
  </br>
