<?php $numberOfPages=ceil($this->questions->count()/$this->questionsPerPage); ?>
<?php $firstIndex = $this->questionsPerPage*($this->currentPageNumber-1); ?>
<?php $lastIndex = min($firstIndex+$this->questionsPerPage, $this->questions->count()); ?>

<table>
  <tr>
    <td><form method="post"><input type="submit" name="first" value="<<"></form></td>
    <td><form method="post"><input type="submit" name="prev" value="<"></form></td>
    <td><form method="post"><input type="submit" name="next" value=">"></form></td>
    <td><form method="post"><input type="submit" name="last" value=">>"></form></td>
    <td><form method="post"> 
          Jump to page 
          <SELECT name="page" onchange="this.form.submit();">
            <?php for($i=1; $i<=$numberOfPages; ++$i) : ?>
              <option value="<?php echo $i; ?>"<?php if ($i == $this->currentPageNumber) echo " selected"; ?>><?php echo $i; ?></option>
            <?php endfor; ?>
          </SELECT>
        </form>
    </td>
  </tr>
</table>

<table class="question">
  <thead class="question">
  	<tr>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/question_id">ID</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/subject_name">Subject</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/category_name">Category</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/source_name">Source</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/title_name">Title</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/answer_type_name">Type</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/username">Creator</a></th>
             <th><a href="<?php echo $this->baseUrl(); ?>/question/index/sortby/question_latex">Latex</a></th>
             <th>Action</th>
  	</tr>
  </thead>

<?php for($i = $firstIndex; $i < $lastIndex; ++$i) :?>
<?php
          $question = $this->questions[$i];
          $validString = ($question->is_valid == 0 ? "Enable" : "Disable");
?>

    <tr> 
      <td><?php echo $this->escape($question->question_id);?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($question->subject_name,$question->subject_id,"Subject#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($question->category_name,$question->category_id,"Category#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($question->source_name,$question->source_id,"Source#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($question->title_name,$question->title_id,"Title#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($question->answer_type_name,$question->answer_type_id,"AnswerType#"));?></td>
      <td><?php echo $this->escape($this->echoIfNotEmpty($question->username,$question->user_id,"User#"));?></td>
      <td><?php echo $this->escape(substr($question->question_latex,0, 75));?></td>
      <td>
        <table border="0">
          <tr>
              <td><a href="<?php echo $this->baseUrl(); ?>/question/view/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $this->escape($question->language_id); ?>">View</a><br/></td>
              <td><a href="<?php echo $this->baseUrl(); ?>/question/edit/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $this->escape($question->language_id); ?>">Edit</a><br/></td>
              <td><a href="<?php echo $this->baseUrl(); ?>/question/translate/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $this->escape($question->language_id); ?>">Translate</a><br/></td>
              <td><a href="<?php echo $this->baseUrl(); ?>/question/disable/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $this->escape($question->language_id); ?>"><?php echo $validString;?></a><br/></td>
              <td><a href="<?php echo $this->baseUrl(); ?>/question/delete/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $this->escape($question->language_id); ?>">Delete</a><br/></td>
<!--              <td><a href="<?php echo $this->baseUrl(); ?>/question/upload/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $this->escape($question->language_id); ?>">Upload SWF</a><br/></td>
-->                     
          </tr>
        </table>  
      </td>
    </tr>
<?php endfor; ?>
  </table>
<table>
  <tr>
    <td><form method="post"><input type="submit" name="first" value="<<"></form></td>
    <td><form method="post"><input type="submit" name="prev" value="<"></form></td>
    <td><form method="post"><input type="submit" name="next" value=">"></form></td>
    <td><form method="post"><input type="submit" name="last" value=">>"></form></td>
    <td><form method="post"> 
          Jump to page 
          <SELECT name="page" onchange="this.form.submit();">
            <?php for($i=1; $i<=$numberOfPages; ++$i) : ?>
              <option value="<?php echo $i; ?>"<?php if ($i == $this->currentPageNumber) echo " selected"; ?>><?php echo $i; ?></option>
            <?php endfor; ?>
          </SELECT>
        </form>
    </td>
  </tr>
</table>
  </br>
