
  <?php foreach($this->questions as $question) : ?>
  <table class="question">
  <thead class="question">
  	<tr>
  		<th>ID</th>
  		<th>Category</th>
  		<th>Question type</th>
  		<th>Action</th>
  	</tr>
  </thead>
    <tr>
      <td><?php echo $this->escape($question->question_id);?></td>
      <td>
        <?php
          //display the correct category depending on the user language
          $categoryInfos = $question->findParentCategory()->findCategoryInfo();
          foreach ($categoryInfos as $categoryInfo) {
            if ($categoryInfo->language_id == $this->user->language_id) {
              echo $this->escape($categoryInfo->name);
            }
          }
        ?>
      </td>
      <td>
        <?php 
          //display the correct category depending on the user language
          $answerTypeInfos = $question->findParentAnswerType()->findAnswerTypeInfo();
          foreach ($answerTypeInfos as $answerTypeInfo) {
            if ($answerTypeInfo->language_id == $this->user->language_id) {
              echo $this->escape($answerTypeInfo->name);
            }
          }
        ?>
          
      <td><a href="<?php echo $this->baseUrl; ?>/question/translate/question_id/<?php echo $this->escape($question->question_id); ?>">Translate</a></td>
		</tr>
		<tr>
      <td>&nbsp;</td>
      <td colspan="3">
      	<table class="question_info">
      	<thead class="question_info">
      		<tr>
      			<th>Language</th>
      			<th>Creation date</th>
        		<th>Created / translated by</th>
        		<th>Is valid</th>
        		<th>Is animated</th>
        		<th>SWF question</th>
        		<th>SWF feedback</th>
        		<th>Groups</th>
        		<th>Comments</th>
        		<th>Action</th>
        	</tr>
        	<tr>
        		<th colspan="5">Question text</th>
        		<th colspan="4">Answer text</th>
        	</tr>
      	</thead>
      <?php 
        //fetch all the question_info for the current question
        $question_infos = $question->findQuestionInfo();
        foreach($question_infos as $question_info) :
      ?>
        <tr>
        	<td><strong><?php echo strtoupper($question_info->findParentLanguage()->name); ?></strong></td>
        	<td><?php echo $this->escape($question_info->creation_date); ?></td>
          <td><?php echo $this->escape($question_info->findParentUser()->username); ?></td>
          <td><?php echo $this->escape($question_info->is_valid); ?></td>
          <td><?php echo $this->escape($question_info->is_animated); ?></td>
          <td>
            <?php 
              if ($question_info->question_flash_file != "") {
                echo "<a href=\"" . $this->flashUrl . $this->escape($question_info->question_flash_file) . "\">" . $this->escape($question_info->question_flash_file) . "</a>";
							}
					  ?>
					</td>
          <td>
            <?php 
              if ($question_info->feedback_flash_file != "") {
                echo "<a href=\"" . $this->flashUrl . $this->escape($question_info->feedback_flash_file) . "\">" . $this->escape($question_info->feedback_flash_file) . "</a>";;
							}
					  ?>
					</td>
					<td>
						<?php 
						  $groups = $question_info->findQuestionGroupViaQuestionGroupQuestion();
						  foreach ($groups as $group) :
						?>
							<a href="<?php echo $this->baseUrl; ?>/group/view/group_id/<?php echo $group->question_group_id?>"><?php echo $group->name ?></a><br/>
						<?php endforeach; ?>
					</td>
					<td>
						<?php
						  $comment_count = count($question_info->findComment());
              if ($comment_count > 0) {
            ?>
            	<a href="<?php echo $this->baseUrl; ?>/question/showComment/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $question_info->language_id; ?>"><?php echo $comment_count ?></a>
            <?php } else { echo $comment_count; } ?>
					</td>
          <td rowspan="2">
          	<a href="<?php echo $this->baseUrl; ?>/question/view/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $question_info->language_id; ?>">View</a><br/>
          	<a href="<?php echo $this->baseUrl; ?>/question/edit/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $question_info->language_id; ?>">Edit</a><br/>
          	<a href="<?php echo $this->baseUrl; ?>/question/disable/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $question_info->language_id; ?>">Disable</a><br/>
          	<a href="<?php echo $this->baseUrl; ?>/question/delete/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $question_info->language_id; ?>">Delete</a><br/>
          	<a href="<?php echo $this->baseUrl; ?>/question/upload/question_id/<?php echo $this->escape($question->question_id); ?>/language_id/<?php echo $question_info->language_id; ?>">Upload SWF</a><br/>
          </td>
        </tr>
        <tr>
        	<td colspan="5"><?php echo $this->escape(substr($question_info->question_latex,0,60)); ?></td>
          <td colspan="4"><?php echo $this->escape(substr($question_info->feedback_latex,0,60)); ?></td>
        </tr>
      <?php endforeach; ?>
        </table>
      </td>
    </tr> 
  </table>
  <br/>
  <?php endforeach; ?>
