<?php if (!empty($this->warning)) : ?>
<div id="warning">
  <?php echo $this->warning; ?>
</div>
<?php endif; ?>
        
<form method="post" action="<?php echo $this->baseUrl(); ?>/question/add">
<div>
  <a href="<?php echo $this->baseUrl(); ?>/question">Cancel and go back to question index</a>
  <input type="submit" name="addQuestionToDB" value="Write to Database">
</div>
         
<br/>

<?php echo $this->render('question/_form.phtml'); ?>

</form>

