<?php echo $this->render('header.phtml'); ?>
<div id="content">
  <h1><?php echo $this->escape($this->title); ?></h1>

  <p><a href="<?php echo $this->baseUrl ?>/question">Cancel and go back to question index</a></p>
	<?php if ($this->step == 1) :?>
	<form method="post" action="add">
		<input type="hidden" name="step" value="1" />
		<div>
			<label for="language">Choose the question language</label>
			<select id="language" name="language">
				<?php foreach($this->languages as $language) : ?>
				<option value="<?php echo $language->language_id; ?>"><?php echo $language->name ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div>
			<input type="submit" name="next" value="Next" />
		</div>
	</form>
	<?php endif; ?>
	
	<?php if ($this->step == 2) :?>
	<div>
		<span>Language:</span>
		<span><?php echo $this->language_name; ?></span>
	</div>
	<form method="post" action="add">
		<input type="hidden" name="step" value="2" />

		<div>
			<label for="subject">Choose the question subject</label>
			<select id="subject" name="subject">
				<?php foreach($this->subjects as $subject) : ?>
				<option value="<?php echo $subject->subject_id; ?>"><?php echo $subject->name ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div>
			<label for="answerType">Choose the type of question</label>
			<select id="answerType" name="answerType">
				<?php foreach($this->answerTypes as $answerType) : ?>
				<option value="<?php echo $answerType->answer_type_id; ?>"><?php echo $answerType->name ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div>
			<input type="submit" name="next" value="Next" />
		</div>
	</form>
	<?php endif; ?>
	
	<?php if ($this->step == 3) :?>
	<div>
		<span>Language:</span>
		<span><?php echo $this->language_name; ?></span>
	</div>
	<div>
		<span>Subject:</span>
		<span><?php echo $this->subject_name; ?></span>
	</div>
	<div>
		<span>Answer type:</span>
		<span><?php echo $this->answer_type_name; ?></span>
	</div>
	
	<form method="post" action="add">
		<input type="hidden" name="step" value="3" />
		<div>
			<label for="category">Choose the question category</label>
			<select id="category" name="category">
				<?php foreach($this->categories as $category) : ?>
					<option value="<?php echo $category->category_id; ?>"><?php echo $category->name; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div>
			<input type="submit" name="next" value="Next" />
		</div>
	</form>
	<?php endif; ?>
	
	<?php if ($this->step == 4) :?>
		<?php echo $this->render('question/_form.phtml'); ?>
	<?php endif; ?>
	
</div>
<?php echo $this->render('question/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>