<form method="post" action="<?php echo $this->baseUrl(); ?>/question/addsource">
  <table>
    <tr>
             <th>Source Name</th>
             <td><input type="text" name="sourceName" value="" size="40"></td>
             <td><input type="submit" name="addSource" value="Submit"></td>
<?php if (!empty($this->formReturnPoint)) : ?>
             <td><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->formReturnPoint;?>">Cancel</a></td>
<?php endif;?>
    </tr>
  </table>
</form>
