<form method="post" action="<?php echo $this->baseUrl(); ?>/question/addtitle">
  <table>
    <tr>
             <th>Title Name</th>
             <td><input type="text" name="titleName" value="" size="40"></td>
             <td><input type="submit" name="addTitle" value="Submit"></td>
<?php if (!empty($this->formReturnPoint)) : ?>
             <td><a href="<?php echo $this->baseUrl(); ?>/<?php echo $this->formReturnPoint;?>">Cancel</a></td>
<?php endif;?>
    </tr>
  </table>
</form>
