<a href="<?php echo $this->baseUrl(); ?>/question">Return</a>

<div id="comment">
  <fieldset>
    <legend>Question comment</legend>
    <table class="question_comment">
      <tr>
        <td><strong>ID</strong></td>
        <td><?php echo $this->question_id; ?></td>
      </tr>
      <tr>
        <td><strong>Comments</strong></td>
        <td><?php $i=1; foreach($this->comments as $comment) { ?>
        <div><?php echo $i++ . "- " . $comment->comment; ?></div><?php } ?>
        </td>
      </tr>
    </table>
  </fieldset>
</div>
