<?php echo $this->render('header.phtml'); ?>
<a href="<?php echo $this->baseUrl ?>/question">Return</a>
<div id="content">
  <h1><?php echo $this->escape($this->title); ?></h1>
  <div id="comment">
  	<fieldset>
  	<legend>Question comment</legend>
  	<table class="question_comment">
  	<tr>
  		<td><strong>ID</strong></td>
  		<td><?php echo $this->question_id; ?></td>
  	</tr>
  	<tr>
  		<td><strong>Comments</strong></td>
  		<td><?php $i=1; foreach($this->comments as $comment) { ?>
		<div><?php echo $i++ . "- " . $comment->comment; ?></div><?php } ?>
		</td>
	</tr>
    	</table>
  	</fieldset>
</div>

</div> 
<?php echo $this->render('question/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>