<form method="post" action="<?php echo $this->baseUrl() ?>/question/delete/question_id/<?php echo $this->question['question_id'] ?>/language_id/<?php echo $this->question['language_id'] ?>">
    <div>
         Are you sure you want to delete this question?
    </div>
    <div>
      <input type="submit" name="deleteQuestion" value="Yes, Delete it" />
      <input type="submit" name="keepQuestion" value="No, Cancel" />
    </div>
</form>

<br/>
<br/>

<?php echo $this->render('question/_display.phtml'); ?>
