<?php if (!empty($this->warning)) : ?>
<div id="warning">
  <?php echo $this->warning; ?>
</div>
<?php endif; ?>

<form method="post" action="<?php echo $this->baseUrl(); ?>/question/edit/question_id/<?php echo $this->question['question_id'];?>/language_id/<?php echo $this->question['language_id'];?>">           
<div>
  <a href="<?php echo $this->baseUrl(); ?>/question">Return</a>
  <input type="submit" name="updateQuestion" value="Write to Database">
</div>

<br/>

<?php echo $this->render('question/_form.phtml'); ?>
</form>
