<?php echo $this->render('header.phtml'); ?>
<a href="<?php echo $this->baseUrl ?>/question">Return</a>
<div id="content">
	<?php if ($this->step == 1) :?>
		<form method="post" action="<?php echo $this->baseUrl ?>/question/<?php echo $this->action ?>/question_id/<?php echo $this->question_id ?>/language_id/<?php echo $this->language_id ?>">
		<input type="hidden" name="step" value="1" />
		<div>
		<div>	<label for="subject">Choose the question subject</label>
			<select id="subject" name="subject">
				<?php foreach($this->subjects as $subject) : ?>
				<option value="<?php echo $subject->subject_id; ?>"><?php echo $subject->name ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div>
			<input type="submit" name="next" value="Next" />
		</div>
	</form>
	<?php endif; ?>
	
	<?php if ($this->step == 2) :?>
		<?php echo $this->render('question/_form.phtml'); ?>
	<?php endif; ?>
  </div>

<?php echo $this->render('question/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>