<div>
<?php echo $this->message; ?>
</div>

<form method="post" action="<?php echo $this->baseUrl(); ?>/question/translate/question_id/<?php echo $this->question['question_id'];?>/language_id/<?php echo $this->from_language_id;?>">
           
<div>
  <a href="<?php echo $this->baseUrl(); ?>/question">Return</a>
  <input type="submit" name="translateQuestion" value="Write to Database">
</div>

<br>

<?php echo $this->render('question/_form.phtml'); ?>
</form>
