<p><a href="<?php echo $this->baseUrl(); ?>/question">Return</a></p>

<div id="message">
  <span class="message"><?php echo $this->escape($this->message);?></span>
</div>

<form method="post" enctype="multipart/form-data" action="<?php echo $this->baseUrl() ?>/question/upload/question_id/<?php echo $this->question['question_id'] ?>/language_id/<?php echo $this->question['language_id'] ?>">
  <table>
  <tr>
    <td><label for="file">Question SWF</label></td>
    <td><input type="file" name="file" /></td>
  </tr>
  <tr>
    <td><input type="submit" name="upload" value="Upload" /></td>
    <td>
        <input type="radio" name="column" value="question" checked/>Question
        <input type="radio" name="column" value="feedback" />Feedback
    </td>
  </tr>
  </table>
</form>
