<?php echo $this->render('header.phtml'); ?>
<div id="content">
  <h1><?php echo $this->escape($this->title); ?></h1>
  
  <?php if ($this->previous_question != null) : ?>
  <div><a href="<?php echo $this->baseUrl ?>/question/view/question_id/<?php echo $this->previous_question->question_id; ?>/language_id/<?php echo $this->question_info->language_id; ?>">Previous</a></div>
  <?php endif; ?>
  
  <?php if ($this->next_question != null) : ?>
  <div><a href="<?php echo $this->baseUrl ?>/question/view/question_id/<?php echo $this->next_question->question_id; ?>/language_id/<?php echo $this->question_info->language_id; ?>">Next</a></div>
  <?php endif; ?>
  
  
  
  <div id="question">
  	<fieldset>
  	<legend>Question details</legend>
  	<table class="view_question_detail">
  	<tr>
  		<td><strong>ID</strong></td>
  		<td><?php echo $this->question->question_id; ?></td>
  	</tr>
  	<tr>
  		<td><strong>Question</strong></td>
  		<td><?php echo $this->question_info->question_latex; ?></td>
  		<td>
  			<?php 
  			  if($this->question_info->question_flash_file != null) {
  			?>
  			  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="500" height="100%">
          <param name="movie" value="<?php echo $this->flashUrl . $this->question_info->question_flash_file;?>">
          <param name="quality" value="high">
          <param name="bgcolor" value="#ffffff" />
          <embed src="<?php echo $this->flashUrl . $this->question_info->question_flash_file;?>" bgcolor="ffffff" quality="high" width="500" height="100%" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" />
          </object>
        <?php 
  			  }
  			?>
  		</td>
  	</tr>
  	<tr>
  		<td><strong>Feedback</strong></td>
  		<td><?php echo $this->question_info->feedback_latex; ?></td>
  		<td>
  			<?php 
  			  if($this->question_info->feedback_flash_file != null) {
  			?>
  			  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="500" height="100%">
          <param name="movie" value="<?php echo $this->flashUrl . $this->question_info->feedback_flash_file;?>">
          <param name="quality" value="high">
          <param name="bgcolor" value="#ffffff" />
          <embed src="<?php echo $this->flashUrl . $this->question_info->feedback_flash_file;?>" bgcolor="ffffff" quality="high" width="500" height="100%" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" />
          </object>
        <?php 
  			  }
  			?>
  		</td>
  	</tr>
  	</table>
  	</fieldset>
	</div>

</div> <!--  end content -->
<?php echo $this->render('question/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>