<p><a href="<?php echo $this->baseUrl(); ?>/question">Return to question index</a></p>

<?php if ($this->show_nav_controls) : ?>
<form method="post">
<input type="hidden" name="question_id" value="<?php echo $this->question['question_id']; ?>">
<input type="hidden" name="language_id" value="<?php echo $this->question['language_id']; ?>">
<table>
  <tr>
    <td><input type="submit" name="first" value="<<"></td>
    <td><input type="submit" name="prev" value="<"></td>
    <td><input type="submit" name="next" value=">"></td>
    <td><input type="submit" name="last" value=">>"></td>
  </tr>
</table>
</form>
<?php endif; ?>

<?php echo $this->render('question/_display.phtml'); ?>
