<form action="<?php echo $this->baseUrl ?>/mailer/<?php echo $this->action ?>" method="post">
	<input type="hidden" name="id" value="<?php echo $this->id;?>">
      <table>
      <tr>
        <td><label for="subject">Subject</label></td>
        <td><input id="subject" type="text" name="subject" size="50" value="<?php echo $this->subject; ?>" /></td>
      </tr>
      <tr>
        <td><label for="body">Body</label></td>
        <td><textarea id="body" name="body" rows="15" cols="80"><?php echo $this->body; ?></textarea></td>
      </tr>
      <tr>
        <td><label for="language">Language</label></td>
        <td>
          <select id="language" name="language">
          <?php foreach ($this->languages as $lang): ?>
          	<?php if ($lang->language_id == $this->language_id) :?>
            	<option selected value="<?php echo $lang->language_id; ?>"><?php echo $lang->short_name; ?></option>
            <?php else : ?>
            	<option value="<?php echo $lang->language_id; ?>"><?php echo $lang->short_name; ?></option>
            <?php endif; ?>
          <?php endforeach; ?>
          </select>
        </td>
      </tr>
      <tr>
        <td colspan="2">
        	<?php if($this->action == "add"): ?>
        		<input type="submit" value="Add">
        	<?php else: ?>
        		<input type="submit" value="Update">
        	<?php endif; ?>
        </td>
      </tr>
      </table>
</form>