<?php echo $this->render('header.phtml'); ?>
  <div id="content">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <form action="<?php echo $this->baseUrl ?>/mailer/add" method="post">
      <table>
      <tr>
        <td><label for="subject">Subject</label></td>
        <td><input id="subject" type="text" name="subject" size="50" /></td>
      </tr>
      <tr>
        <td><label for="body">Body</label></td>
        <td><textarea id="body" name="body" rows="10" cols="50"></textarea></td>
      </tr>
      <tr>
        <td><label for="language">Language</label></td>
        <td>
          <select id="language" name="language">
          <?php foreach ($this->languages as $lang): ?>
            <option value="<?php echo $lang->language_id; ?>"><?php echo $lang->short_name; ?></option>
          <?php endforeach; ?>
          </select>
        </td>
      </tr>
      <tr>
        <td colspan="2"><input type="submit" value="Add"></td>
      </tr>
      </table>
    </form>
  </div>
<?php echo $this->render('mailer/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>