<?php echo $this->render('header.phtml'); ?>
<a href="<?php echo $this->baseUrl ?>/mailer">Return</a>

<div id="content">
  <?php if ($this->step == 1) :?>
		<form method="post" action="<?php echo $this->baseUrl ?>/mailer/<?php echo $this->action ?>/id/<?php echo $this->id; ?>">
		<input type="hidden" name="step" value="1" />
		<div>
			<tr>
				<td><label for="choice">Are you sure you want to delete this mail?</label></td>
				<td><input type="radio" name="choice" value="Yes">Yes
		    	 	    <input type="radio" name="choice" value="No" checked>No
				</td>
			</tr>
		</div>
		<div>
			<input type="submit" name="next" value="Next" />
		</div>
	</form>
   <?php endif; ?>
   
   <?php if ($this->step == 2) :?>
		<form method="post" action="<?php echo $this->baseUrl ?>/mailer/<?php echo $this->action ?>/id/<?php echo $this->id; ?>">
		<input type="hidden" name="step" value="2" />
		<div>
			<?php if ($this->choice=="Yes") echo $this->escape($this->message); ?>
		</div>
		<div>
			<input type="submit" name="finish" value="Finish" />
		</div>
      </form>
   <?php endif; ?>
</div> 
<?php echo $this->render('mailer/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>