<?php echo $this->render('header.phtml'); ?>
    <?php echo $this->message; ?>
    <table class="question">
    <thead class="question">
      <tr>
        <th>Date</th>
        <th>Language</th>
        <th>Subject</th>
        <th>Body</th>
        <th>Action</th>
      </tr>
    </thead>
  <?php foreach($this->mails as $mail): ?>
    <tr>
      <td><?php echo $mail->creation_date; ?></td>
      <td><?php echo $mail->findParentLanguage()->short_name; ?></td>
      <td><?php echo utf8_encode($mail->subject); ?></td>
      <td><?php echo Zend_Filter::get(substr($mail->body,0, 200), 'HtmlEntities'); ?></td>
      <td>
        <a href="<?php echo $this->baseUrl ?>/mailer/send/id/<?php echo $mail->mail_template_id; ?>">Send</a><br/>
        <a href="">Edit(not working)</a><br/>
        <a href="<?php echo $this->baseUrl ?>/mailer/delete/id/<?php echo $mail->mail_template_id; ?>">Delete</a><br/>
      </td>
    </tr>
  <?php endforeach; ?>
  
  </table>
  <div style="padding-left:20px;">
    <a href="<?php echo $this->baseUrl ?>/mailer/add"><strong>Add a new mail</strong></a>
  </div>
<?php echo $this->render('mailer/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>