<?php echo $this->render('header.phtml'); ?>
<a href="<?php echo $this->baseUrl ?>/mailer">Return</a>
  <div id="content">
    <h2><?php echo $this->escape($this->title); ?></h2>
    <?php if ($this->message != null) : ?>
    		<table>
    		<caption style="align:left">Email send result</caption>
    		<thead>
    		<tr>
    			<th>Recipient</th>
    			<th>Result</th>
    		</tr>
    		</thead>
    		<?php foreach ($this->message as $message) : ?>
    		<tr>
    			<td><?php echo $message['recipient']; ?></td>
    			<td>
    			<?php if ($message['success'] == 0) : ?>
    				<span style="color:red">Fail.</span><br/>
    				<small><i><?php echo $message['message']; ?></i></small>
    			<?php else: ?>
    				<span style="color:green">Success.</span><br/>
    			<?php endif; ?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    		</table>
    		<br/>
    <?php endif; ?>
    <table>
    <tr>
      <td>
        <form action="<?php echo $this->baseUrl ?>/mailer/send" method="post">
          <table>
          <thead>
            <tr>
              <th>Recipient list</th>
             </tr>
          </thead>
          <tr>
            <td>
              <input type="hidden" name="id" value="<?php echo $this->mail->mail_template_id; ?>" />
              <span><i>Example</i><br/> "Name1" &lt;mail1@adress.com&gt;,"Name2" &lt;mail2@adress.com&gt;, ...</span><br/>
              <textarea name="to" rows="20" cols="50"></textarea><br/>
            </td>
          </tr>
          <tr>
            <td><input type="submit" value="Send"></td>
          </tr>
          </table>
          
        </form>
      </td>
    </tr>
    <tr>
      <td>
        <span><strong>Subject : </strong></span><span><?php echo utf8_encode($this->mail->subject); ?></span><br/>
        <span><?php echo utf8_encode($this->mail->body); ?></span>
      </td>
    </tr>
    </table>
  </div>
<?php echo $this->render('mailer/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>