<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>

<p><a href="<?php echo $this->baseUrl; ?>/image/add">Add new image</a></p>
<table>
  <tr>
    <th>Logical Name</th>
    <th>Filesystem name</th>
    <th>Creator</th>
    <th>&nbsp;</th>
  </tr>

<?php foreach($this->images as $image) : ?>
  <tr>
    <td><?php echo $this->escape($image->logical_name);?></td>
    <td><?php echo $this->escape($image->physical_name);?></td>
    <td><?php echo $image->findParentRow('User')->username; ?></td>
    <td>
      <a href="<?php echo $this->baseUrl; ?>/image/edit/id/<?php
      echo $image->image_id;?>">Edit</a>
      <a href="<?php echo $this->baseUrl; ?>/image/delete/id/<?php
      echo $image->image_id;?>">Delete</a>
    </td>
  </tr>
  <tr>
    <td colspan="2"><?php echo $this->escape($image->description); ?></td>
  </tr>
<?php endforeach; ?>

</table>
<?php echo $this->render('footer.phtml'); ?>