<?php echo $this->render('header.phtml'); ?>
<div id="content">
	<div id="message">
    <span class="message"><?php echo $this->escape($this->message);?></span>
  </div>
  
  <form action="<?php echo $this->baseUrl ?>/image/upload" enctype='multipart/form-data' method="post">
    <table>
    <tr>
      <td><label for="file">File</label></td>
      <td><input type="file" name="file" /></td>
    </tr>
    <tr>
      <td><label for="description">Description</label></td>
      <td><input type="text" name="description" value=""/></td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="submit" name="upload" value="Upload" />
      </td>
    </tr>
    </table>
  </form>
</div>
<?php echo $this->render('image/_menu.phtml'); ?>
<?php echo $this->render('footer.phtml'); ?>